<?php

namespace backend\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%goods_category}}".
 *
 * @property string $id
 * @property string $title
 * @property string $parent_id
 * @property integer $sort
 * @property string $image
 * @property string $language
 */
class GoodsCategory extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%goods_category}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'sort','type'], 'integer'],
            [['title', 'language'], 'string', 'max' => 50],
            [['image','image2'], 'string', 'max' => 255],
            [['content','sign','subtitle','title2','seo_title','seo_keywords','seo_description'],'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => '名称',
            'subtitle'=>'副标题',
            'title2'=>'标题2',
            'parent_id' => 'Parent ID',
            'sort' => '排序',
            'image' => '图片',
            'language' => 'Language',
            'content'=>'简介',
            'type'=>'展示类型',
            'sign'=>'标签',
            'image2'=>'banner图',
            'seo_title'=>'seo_title',
            'seo_keywords'=>'seo_keywords',
            'seo_description'=>'seo_description',
        ];
    }



    public function beforeSave($insert)
    {
        $this->language=Yii::$app->language;
        if($this->title){
            $this->title3=str_replace(' ','-',strtolower($this->title));
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub


    }


    //关联下级
    public function getChildren()
    {
        return $this->hasMany(GoodsCategory::className(), ['parent_id' => 'id'])->orderBy('sort asc,id desc');
    }


    //关联图标
    public function getIcon()
    {
        return $this->hasMany(CategoryIcon::className(), ['category_id' => 'id'])->orderBy('sort asc,id desc');
    }



    public static function getList(){
        $model=GoodsCategory::find()->where(['language'=>Yii::$app->language])->select(['id','title'])->asArray()->all();
        return ArrayHelper::map($model,'id','title');
    }
}
