<?php

namespace backend\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "{{%position}}".
 *
 * @property string $id
 * @property string $name
 * @property string $type
 * @property string $category
 * @property string $address
 * @property string $mechanism
 * @property integer $sort
 * @property string $created_at
 * @property string $updated_at
 * @property string $language
 * @property string $age
 * @property string $number
 * @property string $education
 * @property string $info
 * @property string $require
 * @property string $work_type
 */
class Position extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%positions}}';
    }


    public function behaviors()
    {
        return [
            TimestampBehavior::className(),

        ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'sort', 'created_at', 'updated_at'], 'integer'],
            [['info', 'require'], 'string'],
            [['name', 'category', 'address', 'mechanism'], 'string', 'max' => 100],
            [['language', 'age', 'number', 'education', 'work_type'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '招聘职位',
            'type' => '类别',
            'category' => '职位类别',
            'address' => '工作地点',
            'mechanism' => '招聘公司',
            'sort' => '排序',
            'created_at' => '添加时间',
            'updated_at' => 'Updated At',
            'language' => 'Language',
            'age'=>'工作年限',
            'number'=>'招聘人数',
            'education'=>'学历',
            'work_type'=>'工作类型',
            'info'=>'岗位职责',
            'require'=>'岗位资格'
        ];
    }

    public function beforeSave($insert)
    {
        $this->language=Yii::$app->language;
        if($this->info){
            $this->info=nl2br($this->info);
        }
        if($this->require){
            $this->require=nl2br($this->require);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function getList($where,$limit=0){
        if($limit>0){
            $model=Position::find()->where($where)->andWhere(['language'=>Yii::$app->language])->limit($limit)->orderBy('sort asc,id desc')->all();
        }else{
            $model=Position::find()->where($where)->andWhere(['language'=>Yii::$app->language])->orderBy('sort asc,id desc')->all();
        }

        return $model;
    }
}
