<?php

namespace backend\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%set_category}}".
 *
 * @property string $id
 * @property integer $type
 * @property string $title
 * @property string $image
 * @property integer $sort
 */
class SetCategory extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%set_category}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'sort'], 'integer'],
            [['title'], 'string', 'max' => 50],
            [['image'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => '类型',
            'title' => '标题',
            'image' => '图片',
            'sort' => '排序',
        ];
    }

    public function beforeSave($insert)
    {
        $this->language=Yii::$app->language;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public static function Category($type){
        $model=SetCategory::find()->where(['type'=>$type])->andWhere(['language'=>Yii::$app->language])->orderBy('sort asc,id desc')->all();
        return ArrayHelper::map($model,'id','title');
    }

    public static function getOne($where){
        $model=SetCategory::find()->where($where)->andWhere(['language'=>Yii::$app->language])->orderBy('sort asc,id desc')->one();
        return $model;
    }

    public static function getList($where){
        $model=SetCategory::find()->where($where)->andWhere(['language'=>Yii::$app->language])->orderBy('sort asc,id desc')->all();
        return $model;
    }



    public static function getList2($where)

    {

        $model = SetCategory::find()->where($where)->orderBy('sort asc,id desc')->all();

        return ArrayHelper::map($model,'title','title');

    }

    public function getChildren(){
        return $this->hasMany(SetImage::className(),['category_id'=>'id'])->orderBy('sort asc,id desc');
    }

}
